#!/usr/bin/env python3
"""
Disk Usage Monitor
==================
Monitors disk usage across all mounted volumes and sends email alerts
when usage exceeds the configured threshold.

Usage:
    python disk_monitor.py --threshold 80 --email admin@company.com
    python disk_monitor.py --threshold 90 --report-only
"""

import argparse
import csv
import json
import shutil
import smtplib
import socket
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Optional


def get_disk_usage() -> list[dict]:
    """Retrieve disk usage for all mounted partitions."""
    volumes = []
    
    try:
        import psutil
        for partition in psutil.disk_partitions(all=False):
            try:
                usage = psutil.disk_usage(partition.mountpoint)
                volumes.append({
                    "device": partition.device,
                    "mountpoint": partition.mountpoint,
                    "fstype": partition.fstype,
                    "total_gb": round(usage.total / (1024**3), 2),
                    "used_gb": round(usage.used / (1024**3), 2),
                    "free_gb": round(usage.free / (1024**3), 2),
                    "percent_used": usage.percent,
                })
            except PermissionError:
                continue
    except ImportError:
        # Fallback using shutil for basic disk check
        total, used, free = shutil.disk_usage("/")
        volumes.append({
            "device": "disk",
            "mountpoint": "/",
            "fstype": "unknown",
            "total_gb": round(total / (1024**3), 2),
            "used_gb": round(used / (1024**3), 2),
            "free_gb": round(free / (1024**3), 2),
            "percent_used": round((used / total) * 100, 1),
        })
    
    return volumes


def check_alerts(volumes: list[dict], threshold: float) -> list[dict]:
    """Return volumes that exceed the alert threshold."""
    return [v for v in volumes if v["percent_used"] >= threshold]


def generate_report(volumes: list[dict], output_path: Optional[str] = None) -> str:
    """Generate a CSV report of disk usage."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = output_path or f"disk_report_{timestamp}.csv"
    
    with open(filename, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=volumes[0].keys())
        writer.writeheader()
        writer.writerows(volumes)
    
    return filename


def send_alert_email(alerts: list[dict], to_email: str, hostname: str) -> None:
    """Send an email alert for volumes over threshold."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"⚠️ DISK ALERT: {hostname} - Critical disk usage detected"
    msg["From"] = "disk-monitor@system.local"
    msg["To"] = to_email
    
    html = f"""
    <html><body>
    <h2>🚨 Disk Usage Alert — {hostname}</h2>
    <p>The following volumes have exceeded the usage threshold:</p>
    <table border="1" cellpadding="8" style="border-collapse:collapse;">
        <tr style="background:#f44336;color:white;">
            <th>Device</th><th>Mount</th><th>Used</th><th>Free</th><th>% Used</th>
        </tr>
    """
    for a in alerts:
        html += f"""
        <tr>
            <td>{a['device']}</td>
            <td>{a['mountpoint']}</td>
            <td>{a['used_gb']} GB</td>
            <td>{a['free_gb']} GB</td>
            <td style="color:red;font-weight:bold;">{a['percent_used']}%</td>
        </tr>
        """
    html += "</table><p><em>Generated by IT Automation Toolkit</em></p></body></html>"
    
    msg.attach(MIMEText(html, "html"))
    
    try:
        with smtplib.SMTP("localhost") as smtp:
            smtp.send_message(msg)
        print(f"✉️  Alert email sent to {to_email}")
    except Exception as e:
        print(f"⚠️  Could not send email (no local SMTP): {e}")
        print("📋 Alert summary printed below instead:")
        for a in alerts:
            print(f"   {a['device']} ({a['mountpoint']}): {a['percent_used']}% used")


def main():
    parser = argparse.ArgumentParser(description="Disk Usage Monitor & Alerter")
    parser.add_argument("--threshold", type=float, default=80.0,
                        help="Alert threshold percentage (default: 80)")
    parser.add_argument("--email", type=str, default=None,
                        help="Email address for alerts")
    parser.add_argument("--report-only", action="store_true",
                        help="Generate report without alerts")
    parser.add_argument("--output", type=str, default=None,
                        help="Output file path for CSV report")
    parser.add_argument("--json", action="store_true",
                        help="Print results as JSON")
    args = parser.parse_args()
    
    hostname = socket.gethostname()
    timestamp = datetime.now().isoformat()
    
    print(f"🔍 Disk Monitor — {hostname} — {timestamp}")
    print(f"   Alert threshold: {args.threshold}%\n")
    
    volumes = get_disk_usage()
    
    if args.json:
        print(json.dumps(volumes, indent=2))
        return
    
    # Print table
    print(f"{'Device':<20} {'Mount':<20} {'Total GB':>10} {'Used GB':>10} {'Free GB':>10} {'%':>6}")
    print("-" * 80)
    for v in volumes:
        status = "🔴" if v["percent_used"] >= args.threshold else "🟢"
        print(f"{status} {v['device']:<18} {v['mountpoint']:<20} {v['total_gb']:>10} "
              f"{v['used_gb']:>10} {v['free_gb']:>10} {v['percent_used']:>5}%")
    
    # Generate report
    if args.output or args.report_only:
        report_file = generate_report(volumes, args.output)
        print(f"\n📄 Report saved: {report_file}")
    
    # Check alerts
    if not args.report_only:
        alerts = check_alerts(volumes, args.threshold)
        if alerts:
            print(f"\n⚠️  {len(alerts)} volume(s) exceed the {args.threshold}% threshold!")
            if args.email:
                send_alert_email(alerts, args.email, hostname)
        else:
            print(f"\n✅ All volumes are below the {args.threshold}% threshold.")


if __name__ == "__main__":
    main()
